---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  labels:
    app: reddit
    component: comment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reddit
      component: comment
  template:
    metadata:
      name: COMMENT_DATABASE_HOST
      labels:
        app: reddit
        component: comment
    spec:
      containers:
      - image: coolerwhite/comment:latest
        name: comment
